### DICTIONARY_EN
POST https://veuitj2bi4.execute-api.us-east-1.amazonaws.com/default/ai-term
Content-Type: application/json
x-api-key: {{awsApiKey}}

{
  "prompt_type": "DICTIONARY_EN",
  "term": "flash"
}

### ENCYCLOPEDIA_EN
POST https://veuitj2bi4.execute-api.us-east-1.amazonaws.com/default/ai-term
Content-Type: application/json
x-api-key: {{awsApiKey}}

{
  "prompt_type": "ENCYCLOPEDIA_EN",
  "term": "Python"
}

### ENCYCLOPEDIA_DE
POST https://veuitj2bi4.execute-api.us-east-1.amazonaws.com/default/ai-term
Content-Type: application/json
x-api-key: {{awsApiKey}}

{
  "prompt_type": "ENCYCLOPEDIA_DE",
  "term": "Mars"
}

### vulnerability analysis (original)
POST https://veuitj2bi4.execute-api.us-east-1.amazonaws.com/default/vulnerability-analysis
Content-Type: application/json
x-api-key: {{awsApiKey}}

{
  "prompt": "CVE-2021-44228"
}
