name: Deploy frontend to S3 and Cloud Fround and the backend Lambda function

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '24'
      PYTHON_VERSION: '3.13'
      AWS_LAMBDA_FUNCTION_NAME: ${{ vars.AWS_LAMBDA_FUNCTION_NAME }}
      VITE_REST_ENDPOINT: ${{ vars.VITE_REST_ENDPOINT }}
      VITE_REST_API_KEY: ${{ secrets.VITE_REST_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Package Lambda function
        working-directory: backend
        run: bash build_lambda.sh

      # terraformed; hardcoding the role ARN temporarily
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: "arn:aws:iam::168424651548:role/tf-ai-term-code-updater"
          role-session-name: ai-term-deploy-${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name "${{ env.AWS_LAMBDA_FUNCTION_NAME }}" \
            --zip-file "fileb://backend/lambda_function.zip" \
            --region "${{ vars.AWS_REGION }}"

      # not yet terraformed
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: ai-term-deploy-${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      # Sync the frontend/dist directory to the specified S3 bucket.
      # The --delete flag removes files in the bucket that are not present in frontend/dist.
      - name: Sync files to S3
        run: |
          aws s3 sync ./frontend/dist s3://${{ vars.S3_BUCKET_NAME }}/ai --delete

      # Invalidate CloudFront distribution cache.
      # This ensures users get the latest version of the files.
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
